services:
  - type: web
    name: anudeep-portfolio-01oi
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.enableCORS false