services:
  - type: web
    name: anudeep-portfolio
    env: python
    plan: free   # <--- ADD THIS LINE HERE!
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0